Controllers/CookFoodController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using ZeroHunger.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using ZeroHunger.Model;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;

namespace ZeroHunger.Controllers
{
    [Route("api/cookFood")]
    [ApiController]
    public class CookFoodController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;
        private User loginUser;

        public CookFoodController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            this._hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            if (@User.Identity.Name != null)
            {
                loginUser = (_db.User.Where(b => b.UserEmail.Equals(@User.Identity.Name)).FirstOrDefault());
                return Json(new { data = await _db.CookedFoodDonation.Where(c => c.DonorUserID.Equals(loginUser.UserID)).ToListAsync() });

            }
            else
            {
                return Json(new { data = await _db.CookedFoodDonation.ToListAsync() });

            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == id);
            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.CookedFoodDonation.Remove(cookFromDb);
            await _db.SaveChangesAsync();
            
            return Json(new { success = true, message = "Delete successful" });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> End(int endID)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == endID);

            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Ending" });
            }
            cookFromDb.RemainQuantity = 0;
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Ended Successfully" });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Add(int addID)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == addID);

            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Increasing" });
            }
            cookFromDb.RemainQuantity += 1;
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Increased Successfully" });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Minus(int minusID)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == minusID);
            
            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Decreasing" });
            }
            cookFromDb.RemainQuantity -= 1;
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Decreased Successfully" });
        }
    }
}

Pages/CookFood/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SocketLabs.InjectionApi;
using SocketLabs.InjectionApi.Message;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using ZeroHunger.Data;
using ZeroHunger.Model;

namespace ZeroHunger.Pages.CookFood
{
    public class IndexModel : PageModel
    {
        private ApplicationDbContext _db;
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IEnumerable<CookedFoodDonation> CFD { get; set; }
        public User u { get; set; }

        public int count { get; set; }
        public int id { get; set; }
        public List<CookedFoodDonation> CFDbyDistance { get; set; }
        public int page {get;set;}
       
        
        public async Task<IActionResult> OnGet()
        {

            string uids=HttpContext.Session.GetString("userid");
            int pp;
            
            string p = Request.Query["page"];
            
            
            int.TryParse(p, out pp);
            page = pp;
            if(p==null)
            {
                page = 0;
            }
            else
            {
                page = pp;
            }
            if(uids==null)
            {
                return RedirectToPage("../login");
            }
            else if (!HttpContext.Request.Cookies["role"].Equals("1"))
             {
                return NotFound();
             }
            int uid;
            int.TryParse(uids, out uid);
            u = await _db.User.FindAsync(uid);
            List<CookReservation> obj =await _db.CookReservation.Where(a => a.userId == uid && a.status.Equals("Pending")).ToListAsync();
            if (obj.Count()==0)
            { 
            CFD = await _db.CookedFoodDonation.ToListAsync();
            count = CFD.Count();
            
            List<CookedFoodDonation> CFDL = new List<CookedFoodDonation>();
            CFDL = CFD.Cast<CookedFoodDonation>().ToList();
           
            CFDL.RemoveAll(x => x.RemainQuantity <= 0);
            CFDL.RemoveAll(x => x.CloseDate <= DateTime.Now);
                if(u.latitude==null)
                {
                    u.latitude = 0;
                }
                if(u.longitute==null)
                {
                    u.longitute = 0;
                }
            foreach(var item in CFDL)
                {
                    
                    item.distance = GetDistance(item.CookLatitude, item.CookLongtitude, (float)u.latitude, (float)u.longitute);
                }
                CFDL.Sort((x,y)=>x.distance.CompareTo(y.distance));
            CFD = (IEnumerable<CookedFoodDonation>)CFDL;
            
                return Page();
            }
            else
            {
                return RedirectToPage("Reservation");
            }
        }

        public async Task OnPost(int ID)
        {
            string uids = HttpContext.Session.GetString("userid");
            int uid;
            int.TryParse(uids, out uid);
            u = await _db.User.FindAsync(uid);
            CookReservation crs = new CookReservation();
            var cfd = await _db.CookedFoodDonation.FindAsync(ID);
            if (cfd.Reservation < cfd.RemainQuantity)
            {
                cfd.Reservation = cfd.Reservation + 1;
                crs.date = System.DateTime.Now.ToString("g");
                crs.reservationRefUser = (_db.User.Where(b => b.UserEmail.Equals(@User.Identity.Name)).FirstOrDefault());
                crs.status = "Pending";
                crs.userId = crs.reservationRefUser.UserID;
                crs.reservationRefCook = (await _db.CookedFoodDonation.FindAsync(ID));
                crs.cookId = crs.reservationRefCook.CookID;
                await _db.CookReservation.AddAsync(crs);
                await _db.SaveChangesAsync();
                var reseruser = await _db.User.FindAsync(crs.userId);
                var cookuser = await _db.User.FindAsync(cfd.DonorUserID);

                string message = "<p style='font-size:large;'> <b style='font-size:x-large;'>Dear " + cookuser.UserName + "</b>,<br/>Your cooked food donation <b>" + cfd.CookName + "</b> which open on " + cfd.OpenDate + " has been <b style='color:green;'>RESERVED</b> by the following receiver:<br/>";
                string message2= "<b>Name:</b> " + reseruser.UserName+ "<br/><b>Phone:</b> " + reseruser.UserPhone+ "<br/><b>Time:</b> " + crs.date+ "<br/><br/><br/><b>" + cfd.CookName+" Remain Quantity:</b>  "+(cfd.RemainQuantity-cfd.Reservation);
                string message3 = "<br/><br/>Thanks,<br/>Zero Hunger<br/><b>This a computer auto-generated email, do not reply to this email.</b></p>";
                anotherSendEmail(message+message2+message3,cookuser.UserEmail);
                CFD = await _db.CookedFoodDonation.ToListAsync();
                Response.Redirect("CookFood");
            }
            else
            {
                Response.Redirect("CookFood");
            }
            
        }
        public async Task<IActionResult> OnPostUpdate(string userLat,string userLon,string handler)
        {
            string userlat = userLat;
            string userlon = userLon;
            string uids = HttpContext.Session.GetString("userid");
            int uid;
            int.TryParse(uids, out uid);
             u = await _db.User.FindAsync(uid);
            float userlatitude;
            float userlongitute;
            float.TryParse(userlat, out userlatitude);
            float.TryParse(userlon, out userlongitute);
            u.latitude = userlatitude;
            u.longitute = userlongitute;
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
        public float GetDistance(float cla,float clo,float ula,float ulo)
        {
            
            float radlat1;
            float radlat2;
            float theta;
            float radtheta;
            float Cdistance;
            radlat1 = (float)(cla * Math.PI  / 180);
            radlat2 = (float)(ula * Math.PI / 180);
            theta = (float)(clo - ulo);
            radtheta = (float)(theta * Math.PI / 180);
            Cdistance = (float)Math.Sin(radlat1) * (float)Math.Sin(radlat2) + (float)Math.Cos(radlat1) * (float)Math.Cos(radlat2) * (float)Math.Cos(radtheta);
            Cdistance = (float)Math.Acos(Cdistance);
            Cdistance = (float)(Cdistance * 180 / Math.PI);//convert to angle
            Cdistance = (float)(Cdistance * 60 * 1.1515);
            Cdistance = (float)(Cdistance * 1.609344);
            decimal d = (decimal)Cdistance;
            d=Decimal.Round(d, 2);
            Cdistance = (float)d;
            return Cdistance;
        }
        public void anotherSendEmail(string emailbody,string userEmail)
        {
            
            var client = new SocketLabsClient(ServerId, "API key"); //Your SocketLabs ServerId and Injection API key

            var message = new BasicMessage();

            message.Subject = "Reservation received";
            message.HtmlBody = emailbody;
            message.PlainTextBody = emailbody;

            message.From.Email = "Your email";//Your email

            //A basic message supports up to 50 recipients and supports several different ways to add recipients
            message.To.Add(userEmail); //Add a To address by passing the email address

            var response = client.Send(message);
        }

    }
}

Pages/CookFoodPage/AddCookFood.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ZeroHunger.Model;
using ZeroHunger.Data;

namespace ZeroHunger.Pages.CookFoodPage
{
    public class AddCookFoodModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public AddCookFoodModel(ApplicationDbContext db)
        {
            _db = db;  
        }
        [BindProperty]
        public CookedFoodDonation cook { get; set; }
        [BindProperty]
        public User donor { get; set; }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            cook.DonorId= (_db.User.Where(b => b.UserEmail.Equals(@User.Identity.Name)).FirstOrDefault());
            if (cook.DonorId == null)
            {
                //ViewData["Message"] = string.Format("Please login first.");
                return RedirectToPage("../login");
            }
            else
            {
                cook.DonorUserID = cook.DonorId.UserID;
                cook.Reservation = 0;
                cook.RemainQuantity = cook.CookQuantity;

                //if (ModelState.IsValid)
                //{
                await _db.CookedFoodDonation.AddAsync(cook);
                await _db.SaveChangesAsync();
                return RedirectToPage("CookFoodView");
            }
            
            //}
            //else
            //{

            //    return RedirectToPage("../Index");
            //}
        }
        
    }
}

Pages/CookFoodPage/CookFoodView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;
using ZeroHunger.Model;
using ZeroHunger.Data;

namespace ZeroHunger.Pages.CookFoodPage
{
    public class CookFoodViewModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public CookFoodViewModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IEnumerable<CookedFoodDonation> cookfood { get; set; }
        public async Task OnGet()
        {
            cookfood = await _db.CookedFoodDonation.ToListAsync();
        }
        public async Task<IActionResult> OnPostDelete(int id)
        {
            var cook= await _db.CookedFoodDonation.FindAsync(id);
            if (cook == null)
            {
                return NotFound();
            }
            _db.CookedFoodDonation.Remove(cook);
            await _db.SaveChangesAsync();

            return RedirectToPage("CookFoodView");
        }
        
    }
}

Pages/CookFoodPage/DonationApplier.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ZeroHunger.Data;
using ZeroHunger.Model;

namespace ZeroHunger.Pages.CookFoodPage
{
    public class DonationApplierModel : PageModel
    {
        private ApplicationDbContext _db;
        public List<CookReservation> CR { get; set; }
        public DonationApplierModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task OnGet()
        {
            int uid;
            
            int cid;
            int.TryParse(Request.Query["cookFood"], out cid);
            string uids=HttpContext.Request.Cookies["userid"];
            int.TryParse(uids, out uid);
            CR = await _db.CookReservation.Where(b => b.cookId.Equals(cid)).ToListAsync();
            
            int c = CR.Count;
            if(c!=0)
             { 
            foreach (var item in CR)
            {
                item.reservationRefCook = await _db.CookedFoodDonation.FindAsync(item.cookId);
                if (item.reservationRefCook.DonorUserID!= uid)
                {
                        Response.Redirect("CookFoodView");
                }
                
            }
            foreach (var item in CR)
            {
                item.reservationRefUser = await _db.User.FindAsync(item.userId);
            }
            }



        }
        public async Task<IActionResult> OnPostConfirm(int id)
        {
            CookReservation c= await _db.CookReservation.FindAsync(id);
            
            if (c == null)
            {
                return NotFound();
            }
            CookedFoodDonation cfd = await _db.CookedFoodDonation.FindAsync(c.cookId);
            cfd.RemainQuantity = cfd.RemainQuantity - 1;
            c.status = "Confirmed";
            await _db.SaveChangesAsync();
            return RedirectToPage("CookFoodView");
        }
    }
}

Pages/CookFoodPage/AddCookFood.cshtml
@page
@model ZeroHunger.Pages.CookFoodPage.AddCookFoodModel
@{
@if (@HttpContext.Request.Cookies["role"] != null && @HttpContext.Request.Cookies["role"].Equals("3"))
{
    <head>
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
</script>
    </head>
    <br />
<h2 style="color:black">Donate Cook Food</h2>
<br />

<ul id="error" style="color: red;">

</ul>
<div class="border container" style="padding:30px">

    <form method="post" class="form-v10-content" id="addForm" enctype="multipart/form-data">
       
        <div class="form-group row">
                 <div class="col-4" style="">
                   <label asp-for="cook.ShopName">Shop Name</label>
                </div>
                <div class="col-6" >
					<input asp-for="cook.ShopName" id="shop" class="form-control" placeholder="Restaurant ABC">
                </div>
               </div>
               <div class="form-group row">
                <div class="col-4" style="">
                   <label asp-for="cook.CookName">Food Name</label>
                </div>
                <div class="col-6" >
					<input asp-for="cook.CookName" id="food" class="form-control" placeholder="Porridge">
                </div>
                </div>
                <div class="form-group row">
                <div class="col-4" style="">
					<label asp-for="cook.CookQuantity">Quantity</label>
					
                </div>
                <div class="col-6">
					<input asp-for="cook.CookQuantity" id="quantity" placeholder="Minimum 5" class="form-control" min='5'>
                </div>
                </div>
                <div class="form-group row">
                <div class="col-4" style="">
					<label asp-for="cook.OpenDate">Opening Time</label>
					
                </div>
                <div class="col-6">
					<input asp-for="cook.OpenDate" type="datetime-local" class="form-control" id="open">
                </div>
                </div>
                <div class="form-group row">
                <div class="col-4" style="">
					<label asp-for="cook.CloseDate">Closing Time</label>
					
                </div>
                <div class="col-6">
					<input asp-for="cook.CloseDate" class="form-control" id="close" >
                </div>
                </div>
                 <div class="form-group row">
                <div class="col-4" style="">
					<label asp-for="cook.CookLatitude">Latitude of your location</label>
							
                </div>
                <div class="col-6">
                   <input asp-for="cook.CookLatitude"  id="la" placeholder="Latitude" class="form-control" readonly required>
                </div>
                </div>
                <div class="form-group row">
				<div class="col-4" style="">
					<label asp-for="cook.CookLongtitude">Longtitude of your location</label>
							
                </div>
                <div class="col-6">
					<input asp-for="cook.CookLongtitude" id="long" placeholder="Longtitude" class="form-control" readonly required>
                    <br>
                    <input type="button" class="btn btn-primary" onclick="navigator.geolocation.getCurrentPosition(getLatLon, error, options);" value="Get Current Location" />
                </div>
                </div>
                @*<div class="col-4">
					<label asp-for="cook.donor.DonorId"></label>
							
                </div>
                <div class="col-6">
					<input asp-for="cook.donor.DonorId" placeholder="Donor ID" required>
                </div>*@
                
				<div id="map" style="width:800px;height:500px;margin:20px auto 20px auto">
    
    <script async defer src="https://maps.googleapis.com/maps/api/js?key="></script>    
    <script>
        //let map, infoWindow;
        function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: -34.397, lng: 150.644 },
        zoom: 6,
    });
    infoWindow = new google.maps.InfoWindow();
    
}

var options = {
    enableHighAccuracy: true,
    timeout: 5000,
    maximumAge: 0
};
function error(err) {
    console.warn(`ERROR(${err.code}): ${err.message}`);
}
 function getLatLon(position){

            var latitude = position.coords.latitude;
            var longitude = position.coords.longitude;
            document.getElementById("la").value=latitude;
            document.getElementById("long").value=longitude;
 map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: -34.397, lng: 150.644 },
        zoom: 6,
        mapId: 'ca3e1b773e1fd477',
    });
 infoWindow = new google.maps.InfoWindow();

if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                (position) => {
                    const pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude,
                    };
                    infoWindow.setPosition(pos);
                    infoWindow.setContent("Location found.");
                    infoWindow.open(map);
                    map.setCenter(pos);
                },
                () => {
                    handleLocationError(true, infoWindow, map.getCenter());
                }
            );
        }
        }
        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(
                browserHasGeolocation
                    ? "Error: The Geolocation service failed."
                    : "Error: Your browser doesn't support geolocation."
            );
            infoWindow.open(map);
        }
		navigator.geolocation.getCurrentPosition(getLatLon);
       
    </script>
</div>
            <div class="form-group row">
                <div class="col-5 offset-4">
                    <input type="submit" value="Create" class="btn btn-primary form-control" />


                </div>
                <br /><br />
                <div class="col-5 offset-4">
                    <a asp-page="CookFoodView" class="btn btn-sucess form-control">Back to List</a>
                </div>
                
             </div>
       </form>
       

        
<script>
$("#addForm").submit(
function(event){
    if(document.getElementById("shop").value=="" || document.getElementById("food").value=="" || document.getElementById("quantity").value==0 || document.getElementById("open").value=="" || document.getElementById("close").value==""){
    var ul =document.getElementById("error");
    while(ul.hasChildNodes()){
        ul.removeChild(ul.firstChild);
    }
    

        if(document.getElementById("shop").value==""){
        var ul = document.getElementById("error");
        var li = document.createElement("li");
        li.appendChild(document.createTextNode("Please enter the shop name."));
        ul.appendChild(li);
    }
    if(document.getElementById("food").value==""){
        var ul = document.getElementById("error");
        var li = document.createElement("li");
        li.appendChild(document.createTextNode("Please enter the food name."));
        ul.appendChild(li);
    }
    if(document.getElementById("quantity").value==0){
        var ul = document.getElementById("error");
        var li = document.createElement("li");
        li.appendChild(document.createTextNode("Donation quantity should be at least 5."));
        ul.appendChild(li);
    }
    var todaysDate = new Date();

    var month;
    if((todaysDate.getMonth()+1)<10){
        month="0"+(todaysDate.getMonth()+1);
    }else{
        month=(todaysDate.getMonth()+1);
    }
    var datetime = todaysDate.getFullYear() + "-" + month + "-" + todaysDate.getDate() + "T" + todaysDate.getHours() + ":" + todaysDate.getMinutes();
    
    if(document.getElementById("open").value==""){
        var ul = document.getElementById("error");
        var li = document.createElement("li");
        li.appendChild(document.createTextNode("Please give an opening time."));
        ul.appendChild(li);
    }
    if(document.getElementById("close").value==""){
        var ul = document.getElementById("error");
        var li = document.createElement("li");
        li.appendChild(document.createTextNode("Please give a closing time."));
        ul.appendChild(li);
    }
    if(document.getElementById("close").value!="" || document.getElementById("open").value!=""){
    if(document.getElementById("open").value<=datetime || document.getElementById("close").value<=datetime){
        var ul = document.getElementById("error");
        var li = document.createElement("li");
        li.appendChild(document.createTextNode("Opening Time or Closing Time had already passed."));
        ul.appendChild(li);
    }
    }
    event.preventDefault();    
    }
else{
        
    }
});
</script>
</div>
<br /><br /><br />
}else{
     <script>
     alert("Sorry, you are not eligible to enter this page.");
     location.href = '/Index';
     </script>
}}

Pages/CookFoodPage/CookFoodView.cshtml
@page
@model ZeroHunger.Pages.CookFoodPage.CookFoodViewModel
@{
    ViewData["Title"] = "Cook Food Donation";
}
<head>
    <link rel="stylesheet" href="~/css/table.css" />
</head>
<br />
<div class="container row p-0 m-0">
    <div class="col-8">
        <h2>Cooked Food Donation</h2>
    </div>
    <div class="col-4">
        <a asp-page="AddCookFood" class="btn btn-info "><i class="bi bi-pencil-square"></i> Donate New Food</a>

        <button align="center" class="btn btn-danger" onclick="javascript:generatePDF();">Generate PDF</button>

    </div>

    <div class="col-18 border p-3" id="printTable">

        <table id="food_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                <tr>
                    <th>Food Name</th>
                    <th>Quantity</th>

                    <th>Opening Time <p style="font-size:x-small;">(MM/DD/YYYY)</p></th>
                    <th>Closing Time <p style="font-size:x-small;">(MM/DD/YYYY)</p></th>


                    <th>Remain Quantity</th>

                    <th>Reserved Quantity</th>

                    <th>Shop Name</th>
                    <th></th>
                </tr>
                </tr>
            </thead>
        </table>
    </div>
</div>
<br />
<br />
<br />
<br />
@section Scripts{
    <script src="~/js/cookFood.js"></script>
}





Pages/CookFoodPage/DonationApplier.cshtml
@page
@model ZeroHunger.Pages.CookFoodPage.DonationApplierModel
@{
}
<br />
<div class="container row p-0 m-0">
    <div class="col-8">
        <h2>Cooked Food Donation</h2>
    </div>
    <div class="col-4">
        <a asp-page="CookFoodView" class="btn btn-info ">Back to List</a>
    </div>
  
            <div class="col-12 border p-3">
                <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>User Name</th>
                            <th>User Contact Number</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>

                    @if (Model.CR.Count != 0)
                    {
                        <form method="post">
                            @foreach (var item in Model.CR)
                            {
                        <tr>
                            <th>@item.date</th>
                            <th>@item.reservationRefUser.UserName</th>
                            <th>@item.reservationRefUser.UserPhone</th>
                            <th>@item.status</th>
                            <th>
                                @if (item.status.Equals("Confirmed")||item.status.Equals("Pending"))
                                { }
                                else
                                {<button class="btn btn-success" style="width:200px;text-align:left;" asp-route-id="@item.Id" asp-page-handler="Confirm"><i class="bi bi-check-square" style="margin:10px 10px 10px 10px;font:red;"></i>Confirm</button>}
                            </th>

                        </tr>
                        }
                            </form>
                        }
                        else
                        {
                            <td colspan="3">No reservation</td>
                        }

                </table>
            </div>
    </div>
   



  