Controllers/CookFoodController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using ZeroHunger.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using ZeroHunger.Model;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;

namespace ZeroHunger.Controllers
{
    [Route("api/cookFood")]
    [ApiController]
    public class CookFoodController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;
        private User loginUser;

        public CookFoodController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            this._hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            if (@User.Identity.Name != null)
            {
                loginUser = (_db.User.Where(b => b.UserEmail.Equals(@User.Identity.Name)).FirstOrDefault());
                return Json(new { data = await _db.CookedFoodDonation.Where(c => c.DonorUserID.Equals(loginUser.UserID)).ToListAsync() });

            }
            else
            {
                return Json(new { data = await _db.CookedFoodDonation.ToListAsync() });

            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == id);
            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _db.CookedFoodDonation.Remove(cookFromDb);
            await _db.SaveChangesAsync();
            
            return Json(new { success = true, message = "Delete successful" });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> End(int endID)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == endID);

            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Ending" });
            }
            cookFromDb.RemainQuantity = 0;
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Ended Successfully" });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Add(int addID)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == addID);

            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Increasing" });
            }
            cookFromDb.RemainQuantity += 1;
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Increased Successfully" });
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Minus(int minusID)
        {
            var cookFromDb = await _db.CookedFoodDonation.FirstOrDefaultAsync(u => u.CookID == minusID);
            
            if (cookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Decreasing" });
            }
            cookFromDb.RemainQuantity -= 1;
            await _db.SaveChangesAsync();

            return Json(new { success = true, message = "Decreased Successfully" });
        }
    }
}

Pages/CookFood/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SocketLabs.InjectionApi;
using SocketLabs.InjectionApi.Message;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using ZeroHunger.Data;
using ZeroHunger.Model;

namespace ZeroHunger.Pages.CookFood
{
    public class IndexModel : PageModel
    {
        private ApplicationDbContext _db;
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IEnumerable<CookedFoodDonation> CFD { get; set; }
        public User u { get; set; }

        public int count { get; set; }
        public int id { get; set; }
        public List<CookedFoodDonation> CFDbyDistance { get; set; }
        public int page {get;set;}
       
        
        public async Task<IActionResult> OnGet()
        {

            string uids=HttpContext.Session.GetString("userid");
            int pp;
            
            string p = Request.Query["page"];
            
            
            int.TryParse(p, out pp);
            page = pp;
            if(p==null)
            {
                page = 0;
            }
            else
            {
                page = pp;
            }
            if(uids==null)
            {
                return RedirectToPage("../login");
            }
            else if (!HttpContext.Request.Cookies["role"].Equals("1"))
             {
                return NotFound();
             }
            int uid;
            int.TryParse(uids, out uid);
            u = await _db.User.FindAsync(uid);
            List<CookReservation> obj =await _db.CookReservation.Where(a => a.userId == uid && a.status.Equals("Pending")).ToListAsync();
            if (obj.Count()==0)
            { 
            CFD = await _db.CookedFoodDonation.ToListAsync();
            count = CFD.Count();
            
            List<CookedFoodDonation> CFDL = new List<CookedFoodDonation>();
            CFDL = CFD.Cast<CookedFoodDonation>().ToList();
           
            CFDL.RemoveAll(x => x.RemainQuantity <= 0);
            CFDL.RemoveAll(x => x.CloseDate <= DateTime.Now);
                if(u.latitude==null)
                {
                    u.latitude = 0;
                }
                if(u.longitute==null)
                {
                    u.longitute = 0;
                }
            foreach(var item in CFDL)
                {
                    
                    item.distance = GetDistance(item.CookLatitude, item.CookLongtitude, (float)u.latitude, (float)u.longitute);
                }
                CFDL.Sort((x,y)=>x.distance.CompareTo(y.distance));
            CFD = (IEnumerable<CookedFoodDonation>)CFDL;
            
                return Page();
            }
            else
            {
                return RedirectToPage("Reservation");
            }
        }

        public async Task OnPost(int ID)
        {
            string uids = HttpContext.Session.GetString("userid");
            int uid;
            int.TryParse(uids, out uid);
            u = await _db.User.FindAsync(uid);
            CookReservation crs = new CookReservation();
            var cfd = await _db.CookedFoodDonation.FindAsync(ID);
            if (cfd.Reservation < cfd.RemainQuantity)
            {
                cfd.Reservation = cfd.Reservation + 1;
                crs.date = System.DateTime.Now.ToString("g");
                crs.reservationRefUser = (_db.User.Where(b => b.UserEmail.Equals(@User.Identity.Name)).FirstOrDefault());
                crs.status = "Pending";
                crs.userId = crs.reservationRefUser.UserID;
                crs.reservationRefCook = (await _db.CookedFoodDonation.FindAsync(ID));
                crs.cookId = crs.reservationRefCook.CookID;
                await _db.CookReservation.AddAsync(crs);
                await _db.SaveChangesAsync();
                var reseruser = await _db.User.FindAsync(crs.userId);
                var cookuser = await _db.User.FindAsync(cfd.DonorUserID);

                string message = "<p style='font-size:large;'> <b style='font-size:x-large;'>Dear " + cookuser.UserName + "</b>,<br/>Your cooked food donation <b>" + cfd.CookName + "</b> which open on " + cfd.OpenDate + " has been <b style='color:green;'>RESERVED</b> by the following receiver:<br/>";
                string message2= "<b>Name:</b> " + reseruser.UserName+ "<br/><b>Phone:</b> " + reseruser.UserPhone+ "<br/><b>Time:</b> " + crs.date+ "<br/><br/><br/><b>" + cfd.CookName+" Remain Quantity:</b>  "+(cfd.RemainQuantity-cfd.Reservation);
                string message3 = "<br/><br/>Thanks,<br/>Zero Hunger<br/><b>This a computer auto-generated email, do not reply to this email.</b></p>";
                anotherSendEmail(message+message2+message3,cookuser.UserEmail);
                CFD = await _db.CookedFoodDonation.ToListAsync();
                Response.Redirect("CookFood");
            }
            else
            {
                Response.Redirect("CookFood");
            }
            
        }
        public async Task<IActionResult> OnPostUpdate(string userLat,string userLon,string handler)
        {
            string userlat = userLat;
            string userlon = userLon;
            string uids = HttpContext.Session.GetString("userid");
            int uid;
            int.TryParse(uids, out uid);
             u = await _db.User.FindAsync(uid);
            float userlatitude;
            float userlongitute;
            float.TryParse(userlat, out userlatitude);
            float.TryParse(userlon, out userlongitute);
            u.latitude = userlatitude;
            u.longitute = userlongitute;
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
        public float GetDistance(float cla,float clo,float ula,float ulo)
        {
            
            float radlat1;
            float radlat2;
            float theta;
            float radtheta;
            float Cdistance;
            radlat1 = (float)(cla * Math.PI  / 180);
            radlat2 = (float)(ula * Math.PI / 180);
            theta = (float)(clo - ulo);
            radtheta = (float)(theta * Math.PI / 180);
            Cdistance = (float)Math.Sin(radlat1) * (float)Math.Sin(radlat2) + (float)Math.Cos(radlat1) * (float)Math.Cos(radlat2) * (float)Math.Cos(radtheta);
            Cdistance = (float)Math.Acos(Cdistance);
            Cdistance = (float)(Cdistance * 180 / Math.PI);//convert to angle
            Cdistance = (float)(Cdistance * 60 * 1.1515);
            Cdistance = (float)(Cdistance * 1.609344);
            decimal d = (decimal)Cdistance;
            d=Decimal.Round(d, 2);
            Cdistance = (float)d;
            return Cdistance;
        }
        public void anotherSendEmail(string emailbody,string userEmail)
        {
            
            var client = new SocketLabsClient(ServerId, "API key"); //Your SocketLabs ServerId and Injection API key

            var message = new BasicMessage();

            message.Subject = "Reservation received";
            message.HtmlBody = emailbody;
            message.PlainTextBody = emailbody;

            message.From.Email = "Your email";//Your email

            //A basic message supports up to 50 recipients and supports several different ways to add recipients
            message.To.Add(userEmail); //Add a To address by passing the email address

            var response = client.Send(message);
        }

    }
}

Pages/CookFood/Reservation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SocketLabs.InjectionApi;
using SocketLabs.InjectionApi.Message;
using ZeroHunger.Data;
using ZeroHunger.Model;

namespace ZeroHunger.Pages.CookFood
{

    public class ReservationModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public ReservationModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IEnumerable<CookedFoodDonation> CFD { get; set; }
        public IEnumerable<CookReservation> CR { get; set; }
        public IEnumerable<CookReservation> CRP { get; set; }
        public User donor { get; set; }


        public async Task<IActionResult> OnGet()
        {
            int uid;
            int.TryParse(HttpContext.Session.GetString("userid"), out uid);
            string uids = HttpContext.Session.GetString("userid");
            if (uids == null)
            {
                return RedirectToPage("../login");
            }
            else
            {
                if (!HttpContext.Request.Cookies["role"].Equals("1"))
                {

                    return NotFound();
                }

            }
            CR = await _db.CookReservation.Where(b => b.userId==uid).ToListAsync();
            foreach (var item in CR)
            {
                item.reservationRefCook = await _db.CookedFoodDonation.FindAsync(item.cookId);
            }
            if (CR.Count() != 0)
            {
                donor = await _db.User.FindAsync(CR.ElementAt(0).reservationRefCook.DonorUserID);
            }
            CRP = CR.Where(c => c.status.Equals("Pending"));

            CR = CR.Where(c => c.status.Equals("Success") || c.status.Equals("Expired")||c.status.Equals("Confirmed"));
            return Page();

        }
        public async Task<IActionResult> OnPostComplete(int id)
        {
            var CookReservation = await _db.CookReservation.FindAsync(id);
            if (CookReservation == null)
            {
                return NotFound();
            }
            CookReservation.status = "Success";
            await _db.SaveChangesAsync();
            return RedirectToPage("Reservation");
        }
        public async Task<IActionResult> OnPostCancel(int id)
        {
            CookReservation Cookreservation = await _db.CookReservation.FindAsync(id);
            if (Cookreservation == null)
            {
                return NotFound();
            }
            var cfd = await _db.CookedFoodDonation.FindAsync(Cookreservation.cookId);
            cfd.Reservation = cfd.Reservation - 1;
            _db.CookReservation.Remove(Cookreservation);
            await _db.SaveChangesAsync();
            var reseruser = await _db.User.FindAsync(Cookreservation.userId);
            var cookuser = await _db.User.FindAsync(cfd.DonorUserID);
            string message = "<p style='font-size:large;'> <b style='font-size:x-large;'>Dear " + cookuser.UserName + "</b>,<br/>Your cooked food donation <b>" + cfd.CookName + "</b> which open on " + cfd.OpenDate + " has been <b style='color:red'>CANCELED</b> by the following receiver:<br/>";
            string message2 = "<b>Name:</b> " + reseruser.UserName + "<br/><b>Phone:</b> " + reseruser.UserPhone + "<br/><b>Time:</b> " + Cookreservation.date + "<br/><b>" + cfd.CookName + " Remain Quantity:</b>  " + cfd.RemainQuantity;
            string message3 = "<br/><br/>Thanks,<br/>Zero Hunger<br/><b>This a computer auto-generated email, do not reply to this email.</b></p>";
            anotherSendEmail(message + message2 + message3, cookuser.UserEmail);
            return RedirectToPage("Reservation");
        }
        public void anotherSendEmail(string emailbody, string userEmail)
        {
            
            var client = new SocketLabsClient(ServerID, "API Key"); //Your SocketLabs ServerId and Injection API key

            var message = new BasicMessage();

            message.Subject = "Reservation Canceled";
            message.HtmlBody = emailbody;
            message.PlainTextBody = emailbody;

            message.From.Email = "Your Email";//Your Email

            //A basic message supports up to 50 recipients and supports several different ways to add recipients
            message.To.Add(userEmail); //Add a To address by passing the email address

            var response = client.Send(message);
        }


    }
}

Pages/CookFood/Index.cshtml
@page
@model ZeroHunger.Pages.CookFood.IndexModel

<div style="display:flex;justify-content:center;margin-bottom:20px;" >
    <h1 style="text-align:center;margin:0px 20px 0px 20px ;">Cook Food Donation</h1>
   
    <form method="post" id="updateForm" asp-page-handler="Update">
        <input type="hidden" name="handler" value="Update" />
        <input type="hidden" id="userLat" name="userLat" value="@Model.u.latitude" />
        <input type="hidden" id="userLon" name="userLon" value="@Model.u.longitute" />
        <button class="btn btn-info" onclick="navigator.geolocation.getCurrentPosition(fillLatLon, error, options); return false;">Update Location</button>

    </form>
</div>
        <div class='promptContainer' id="promptContainer">
            <div style="display:flex;justify-content:center;background-color:transparent;">
                <div class='promptTitle'>Donation   <i class="bi bi-x-square-fill" onClick="closeRePrompt();" id="closeWindow"></i></div>
                
            </div>
            <form method="post">
                <div style="display: flex; justify-content: center; background-color: transparent;">

                    <table>
                        <tr>
                            <th class='tableLeft'>Shop Name</th>
                            <td id='pFoodShopName' class='tableLeft'></td>
                        </tr>
                        <tr>
                            <th class='tableLeft'>Food Name</th>
                            <td id='pFoodName' class='tableLeft'></td>
                        </tr>
                        <tr>
                            <th class='tableLeft'>Quantity</th>
                            <td id="pFoodQuantity" class='tableLeft'></td>
                        </tr>
                        <tr>
                            <th class='tableLeft'>Distance</th>
                            <td id="pFoodDistance" class='tableLeft'></td>
                        </tr>

                    </table>
                    <input id="pFoodId" type="hidden" asp-for="id" value="0" />

                </div>
                <div style="display: flex; justify-content: center; background-color: transparent;">
                    <input type='submit' value='Reserve' class="btn" id='reservedBut'>
                </div>
            </form>
        </div>

        <div id="CookFoodContainer">
            <div id="map" style="width:80vw;height:80vh;"class="d-xl-block d-none">
                <script async defer src="https://maps.googleapis.com/maps/api/js?key="></script>
               
            </div>
            
            
            <div id="list">
                

                <div id="pageButtonContainer">

                    <a href="CookFood?page=@(Model.page - 1)" id="pPage" class="btn btn-info"><</a>
                    

                </div>

                @if (Model.CFD.Count() == 0)
                {
                    <p>No Cooked Food In List</p>
                }
                else
                {
               
                    @for (int i = Model.page * 4; i < Model.CFD.Count()&&i<=Model.page+3; i++)
                {
            <div id="itemContainer" name="itemContainer" onClick="displayItemBox('@Model.CFD.ElementAt(i).ShopName', '@Model.CFD.ElementAt(i).CookName', ' @(Model.CFD.ElementAt(i).RemainQuantity-Model.CFD.ElementAt(i).Reservation)', '@Model.CFD.ElementAt(i).CookID')">
                <div id="itemInfo">
                    <div>
                        <div id="itemName" name="itemName">
                            @Model.CFD.ElementAt(i).CookName

                        </div>
                        <div id="itemQuantity">
                            @(Model.CFD.ElementAt(i).RemainQuantity- Model.CFD.ElementAt(i).Reservation)/@Model.CFD.ElementAt(i).RemainQuantity
                        </div>
                    </div>
                    <p hidden id="itemCount">@Model.count</p>
                    <p hidden name="itemLat">@Html.DisplayFor(m => Model.CFD.ElementAt(i).CookLatitude)</p>
                    <p hidden name="itemLon">@Html.DisplayFor(m => Model.CFD.ElementAt(i).CookLongtitude)</p>


                    <div name="itemDistance" id="itemDistance.@Model.CFD.ElementAt(i).CookID">
                        <b>@Html.DisplayFor(m => Model.CFD.ElementAt(i).distance) km</b>
                    </div>
                </div>

            </div>
                }
                    @foreach (var item in Model.CFD)
                    {


                        


                    }


                }
            <div id="pageButtonContainer">

                
                <a href="CookFood?page=@(Model.page+1)" id="pPage" class="btn btn-info">></a>

            </div>
            </div>

        </div>
        
 

Pages/CookFood/Reservation.cshtml
@page
@model ZeroHunger.Pages.CookFood.ReservationModel
@{
}

<div id="ReservationPageContainer">
    <div style="display:flex;flex-direction:column;">
        <div id="Reservation" class="ReservationTitle" onclick="Change(document.getElementById('History'),this)">Reservation</div>
        <div id="History" onclick="Change(document.getElementById('Reservation'),this)">History</div>
    </div>
        
</div>
<div id="ReservationContainer">
    @if (Model.CRP.Count() == 0)
    {
    <p>No Reservation</p>
    }
    else
    {
    @foreach (var item in Model.CRP)
        {
<table style="margin:10px 0px 10px 10px">
    <form method="post">
    <tr>
        <th>Reservation Date</th>
        <th>Shop</th>
        <th>Food</th>
        <th>Phone</th>
        <th><button class="btn btn-success" style="width:200px;text-align:left;" asp-route-id="@item.Id" asp-page-handler="Complete"><i class="bi bi-check-square" style="margin:10px 10px 10px 10px;font:red;"></i>Complete</button></th>


    </tr>

    <tr>
        <td>@item.date</td>
        <td>@item.reservationRefCook.ShopName</td>
        <td>@item.reservationRefCook.CookName</td>
        <td>@Model.donor.UserPhone</td>
        <th><button class="btn btn-danger" style="width:200px;text-align:left;" asp-route-id="@item.Id" asp-page-handler="Cancel"><i class="bi bi-x" style="margin:10px 10px 10px 10px;font:red;"></i>Cancel</button></th>

    </tr>

    </form>

    <div id="itemCount" style="display:none;">1</div>
    <input hidden name="itemLat" value="@item.reservationRefCook.CookLatitude" />
    <input hidden name="itemLon" value="@item.reservationRefCook.CookLongtitude" />

</table>
    <div id="map" style="width:100%;height:500px;">
        Map
        <script async defer src="https://maps.googleapis.com/maps/api/js?key="></script>
    </div>
        }
    }

</div>

<div id="HistoryContainer">
   
    <div>
        <button align="right" class="btn btn-danger" style="margin:10px 0px 10px 0px;float:right;" onclick="javascript:generatePDF();">Generate PDF</button>
    </div>
    
    <div class="col-12 p-3" id="printTable">
        
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Shop</th>
                    <th>Food</th>
                    <th>Status</th>
                </tr>
            </thead>

            @*@foreach (var item in Model.CR)
            {
                <tr>
                    <td>@item.date</td>
                    <td>@item.reservationRefCook.ShopName</td>
                    <td>@item.reservationRefCook.CookName</td>
                    <td>@item.status</td>
                </tr>

            }*@
        </table>
    </div>
</div>


@section Scripts{
    <script src="~/js/JavaScript.js"></script>
    <script>
        function generatePDF() {
            var pTable = document.getElementById('printTable').innerHTML;
            var win = window.open('', '', 'height=100%,width=100%');
            win.document.write('<html><head><title>Reservation History </title>');
            win.document.write('<style> h2{text-align:center;} #printTable{margin-left:auto; margin-right:auto;} th,td{border: 1px solid black;} table,th,td{ border-collapse:collapse; margin:20px auto;} th:last-child,td:last-child{display:none; border:0;} td{text-align:center;}</style>');
            win.document.write('</head><body>');
            win.document.write('<h2>Reservation History </h2>');
            win.document.write(pTable);
            win.document.write('</body></html>');
            win.document.close();
            win.print();
            setTimeout(function () { win.close() }, 500);
        }
    </script>
}